[project]
name = 'Tokenized-Manufacturing-Equipment-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.condition-verification]
path = 'contracts/condition-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.seller-verification]
path = 'contracts/seller-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
